### ISSUE TITLE
i have an error when i launch the bot 

### ISSUE THREAD

**Issue by Toru-yy** [Katrixerse/Corius#10]
PS C:\Users\Shadow\Documents\yyu> node app.js
Connected!
tokito. loaded. Currently in 1 server(s) with 6 users.
401 Unauthorized
401 Unauthorized
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined     
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\events\client\message.js:16:24)
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)   
    at Query.EofPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:38:16)
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\events\client\message.js:16:24)
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)   
    at Query.EofPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:38:16)
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\events\client\message.js:16:24)
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)   
    at Query.EofPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:38:16)
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\events\client\message.js:16:24)
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)   
    at Query.EofPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:38:16)
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\events\client\message.js:16:24)
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)   
    at Query.EofPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:38:16)
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\events\client\message.js:16:24)
    at Query.<anonymous> (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)   
    at Query.EofPacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Shadow\Documents\yyu\node_modules\mysql\lib\protocol\Protocol.js:38:16)

**Comment by Toru-yy** [comment]
and this is when i launch a command

**Comment by Katrixerse** [comment]
Already have had this issue opened please look at closed issues.

**Comment by Toru-yy** [comment]
> Already have had this issue opened please look at closed issues.

Yeah but no solution

**Comment by Toru-yy** [comment]
pls help

**Comment by Katrixerse** [comment]
Have you changed the info in dbconnection.js

**Comment by Toru-yy** [comment]
> Have you changed the info in dbconnection.js

yeah, this is the error after i success to connect this to my db

**Comment by Katrixerse** [comment]
Does the user have the correct permissions it needs to use the db?

I will try and testing tomorrow morning and see if I can get it setup still its been awhile since I've tried.

**Comment by Toru-yy** [comment]
> Does the user have the correct permissions it needs to use the db?
> 
> I will try and testing tomorrow morning and see if I can get it setup still its been awhile since I've tried.

yes he have all permissions to the db bc i grant all privileges to database to root user

here a image of the error 

![image](https://user-images.githubusercontent.com/68610031/89710970-9f9e8580-d987-11ea-8691-4c2d582f98d3.png)

**Comment by Toru-yy** [comment]
and the error appear when i say i a message if not i have 0 error

**Comment by Toru-yy** [comment]
can i have a reponse plz i need this for 1 week the bot xD

**Comment by Katrixerse** [comment]
> can i have a reponse plz i need this for 1 week the bot xD

Why is that.

**Comment by Toru-yy** [comment]
> > can i have a reponse plz i need this for 1 week the bot xD
> 
> Why is that.

:/ idk

**Comment by buttermiilk** [comment]
> 401 Unauthorized 
Cannot read 'prefix'

Hmm

**Comment by Katrixerse** [comment]
I have set up the mysql db on Ubuntu and changed dbConnection.js and unable to get this issue im guessing you dont have the server setup correctly or the connection info is wrong, Ill continue testing this though incase theres something else i might be missing.

Might help:
[401 Error with mysql](https://community.auth0.com/t/401-unauthorized-error-when-connecting-to-custom-mysql-database/40024)
