### ISSUE TITLE
Error message while sanding any message

### ISSUE THREAD

**Issue by Fleax1** [Katrixerse/Corius#2]
**Describe the bug**
No command works
While sending any message, error appear : 

`[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (D:\wamp64\www\Corius\events\client\message.js:16:24)
    at Query.<anonymous> (D:\wamp64\www\Corius\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (D:\wamp64\www\Corius\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (D:\wamp64\www\Corius\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (D:\wamp64\www\Corius\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)
    at Query.EofPacket (D:\wamp64\www\Corius\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (D:\wamp64\www\Corius\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\wamp64\www\Corius\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\wamp64\www\Corius\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\wamp64\www\Corius\node_modules\mysql\lib\protocol\Protocol.js:38:16)`

**To Reproduce**
Clone the repository
npm install
change token and dbConnection

**Expected behavior**
no error message ...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Katrixerse** [comment]
This should now be fixed i accidentally did guildID instead of guidId in the sql statement which would cause the error i will have to test this later on to make sure.
