### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by thewolf87** [Katrixerse/Corius#3]
Please help me I am getting this error I don't know how do I fix this

`Error: Cannot find module 'm3u8stream/lib/parse-time'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/rbd/pnpm-volume/b21c327f-8cd4-4ebe-92ea-6b88251c783e/node_modules/.registry.npmjs.org/ytdl-core/0.29.7/node_modules/ytdl-core/lib/info-extras.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)`

**Comment by Katrixerse** [comment]
https://stackoverflow.com/questions/58965713/cannot-find-module-m3u8stream-lib-parse-time

This has already been reported but seems to be an issue with the package ytdl-core instead of the bot, but ill try and see what i can do.

**Comment by x-sNOw** [comment]
just install the newest YTDL-CORE or:
cd node_modules/ytdl-core/lib
vim index.js and edit m3u8stream/lib/parse-time to m3u8stream/dist/parse-time
proceed to do the same in infox-extras.js

**Comment by Katrixerse** [comment]
Should be now fixed and downloads the proper version and a issue fixed with security because minimist was using an outdated version.
