### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by niikoolaa04** [Katrixerse/Corius#6]
So, i'm hosting your bot on my VPS and it starts and everything is good, bot is online, but when i enter any message in discord channel chat it gives error in console (vps), if i try any bot command it's not working like, error is down below

`
401 Unauthorized
401 Unauthorized
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (/home/Radovan/events/client/message.js:16:24)
    at Query.<anonymous> (/home/Radovan/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/home/Radovan/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/home/Radovan/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/Radovan/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/Radovan/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/Radovan/node_modules/mysql/lib/protocol/Protocol.js:38:16)
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (/home/Radovan/events/client/message.js:16:24)
    at Query.<anonymous> (/home/Radovan/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/home/Radovan/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/home/Radovan/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/Radovan/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/Radovan/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/Radovan/node_modules/mysql/lib/protocol/Protocol.js:38:16)
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (/home/Radovan/events/client/message.js:16:24)
    at Query.<anonymous> (/home/Radovan/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/home/Radovan/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/home/Radovan/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/Radovan/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/Radovan/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/Radovan/node_modules/mysql/lib/protocol/Protocol.js:38:16)
[unhandledRejection] Reason: TypeError: Cannot read property 'prefix' of undefined
    at Query.<anonymous> (/home/Radovan/events/client/message.js:16:24)
    at Query.<anonymous> (/home/Radovan/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/home/Radovan/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/home/Radovan/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/home/Radovan/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/Radovan/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/Radovan/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/Radovan/node_modules/mysql/lib/protocol/Protocol.js:38:16)

`

**Comment by Katrixerse** [comment]
Have you changed the info in dbconnection.js, and if so you have made the db and given the user full perms to use the db that your using for it, also have to make sure the port it uses is open for it.

**Comment by thsanki** [comment]
> Have you changed the info in dbconnection.js, and if so you have made the db and given the user full perms to use the db that your using for it, also have to make sure the port it uses is open for it.

From where we get host username password please provide link where in free we create it

**Comment by Katrixerse** [comment]
> > Have you changed the info in dbconnection.js, and if so you have made the db and given the user full perms to use the db that your using for it, also have to make sure the port it uses is open for it.
> 
> From where we get host username password please provide link where in free we create it

it gives a link how to set up mysql in the read me
You have to create the mysql user and set a password or alternatively can host in on the same server and use the root user if you really want.

So host would be localhost and user would be root and would just need to give it a password and fill the password in dbconnection.js don't need to worry about the port as thats the default unless your host closes it and then would have to request for it.

There isn't really good free hosting  host it locally than which shouldn't be a issue for personal use anyways, glitch won't work for the mysql server, heroku might work but I have no experience with.
